
spring.datasource.url=jdbc:postgresql://localhost:5432/Pulse
spring.datasource.username=postgres
spring.datasource.password="ENTER YOUR PASSWORD HERE"
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=pulsepoint
#port
server.port=8080 
